# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\sviluppo\Roam\src\roam\ui\ui_annotationdock.ui'
#
# Created: Thu Mar 12 14:47:54 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(188, 785)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet(_fromUtf8(""))
        self.infoframe = QtGui.QFrame(Form)
        self.infoframe.setGeometry(QtCore.QRect(9, 9, 178, 771))
        self.infoframe.setMaximumSize(QtCore.QSize(178, 16777215))
        self.infoframe.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.infoframe.setStyleSheet(_fromUtf8("background:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(232, 228, 226, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
""))
        self.infoframe.setFrameShape(QtGui.QFrame.Panel)
        self.infoframe.setFrameShadow(QtGui.QFrame.Raised)
        self.infoframe.setObjectName(_fromUtf8("infoframe"))
        self.closeBarButton = QtGui.QToolButton(self.infoframe)
        self.closeBarButton.setGeometry(QtCore.QRect(0, 0, 178, 44))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeBarButton.sizePolicy().hasHeightForWidth())
        self.closeBarButton.setSizePolicy(sizePolicy)
        self.closeBarButton.setMinimumSize(QtCore.QSize(178, 0))
        self.closeBarButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.closeBarButton.setStyleSheet(_fromUtf8("background: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #eef, stop: 1 #ccf);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"subcontrol-position: top center;\n"
""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cancel")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBarButton.setIcon(icon)
        self.closeBarButton.setIconSize(QtCore.QSize(35, 35))
        self.closeBarButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.closeBarButton.setAutoRaise(True)
        self.closeBarButton.setObjectName(_fromUtf8("closeBarButton"))
        self.navwidget = QtGui.QWidget(self.infoframe)
        self.navwidget.setGeometry(QtCore.QRect(10, 47, 158, 715))
        self.navwidget.setMaximumSize(QtCore.QSize(158, 16777215))
        self.navwidget.setObjectName(_fromUtf8("navwidget"))
        self.gridLayout = QtGui.QGridLayout(self.navwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.PointButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PointButton.sizePolicy().hasHeightForWidth())
        self.PointButton.setSizePolicy(sizePolicy)
        self.PointButton.setMinimumSize(QtCore.QSize(58, 41))
        self.PointButton.setMaximumSize(QtCore.QSize(58, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/capture-point")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PointButton.setIcon(icon1)
        self.PointButton.setIconSize(QtCore.QSize(35, 35))
        self.PointButton.setCheckable(True)
        self.PointButton.setChecked(False)
        self.PointButton.setAutoExclusive(True)
        self.PointButton.setAutoRaise(True)
        self.PointButton.setObjectName(_fromUtf8("PointButton"))
        self.gridLayout.addWidget(self.PointButton, 0, 0, 1, 1)
        self.paintButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paintButton.sizePolicy().hasHeightForWidth())
        self.paintButton.setSizePolicy(sizePolicy)
        self.paintButton.setMinimumSize(QtCore.QSize(58, 41))
        self.paintButton.setMaximumSize(QtCore.QSize(58, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/freeDraw.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paintButton.setIcon(icon2)
        self.paintButton.setIconSize(QtCore.QSize(35, 35))
        self.paintButton.setCheckable(True)
        self.paintButton.setAutoExclusive(True)
        self.paintButton.setAutoRaise(True)
        self.paintButton.setObjectName(_fromUtf8("paintButton"))
        self.gridLayout.addWidget(self.paintButton, 0, 1, 1, 1)
        self.lineButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineButton.sizePolicy().hasHeightForWidth())
        self.lineButton.setSizePolicy(sizePolicy)
        self.lineButton.setMinimumSize(QtCore.QSize(58, 41))
        self.lineButton.setMaximumSize(QtCore.QSize(58, 41))
        self.lineButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/capture-line")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lineButton.setIcon(icon3)
        self.lineButton.setIconSize(QtCore.QSize(35, 35))
        self.lineButton.setCheckable(True)
        self.lineButton.setAutoExclusive(True)
        self.lineButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.lineButton.setAutoRaise(True)
        self.lineButton.setObjectName(_fromUtf8("lineButton"))
        self.gridLayout.addWidget(self.lineButton, 1, 0, 1, 1)
        self.polyButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polyButton.sizePolicy().hasHeightForWidth())
        self.polyButton.setSizePolicy(sizePolicy)
        self.polyButton.setMinimumSize(QtCore.QSize(58, 41))
        self.polyButton.setMaximumSize(QtCore.QSize(58, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/capture-polygon")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polyButton.setIcon(icon4)
        self.polyButton.setIconSize(QtCore.QSize(35, 35))
        self.polyButton.setCheckable(True)
        self.polyButton.setAutoExclusive(True)
        self.polyButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.polyButton.setAutoRaise(True)
        self.polyButton.setObjectName(_fromUtf8("polyButton"))
        self.gridLayout.addWidget(self.polyButton, 1, 1, 1, 1)
        self.rectangleButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rectangleButton.sizePolicy().hasHeightForWidth())
        self.rectangleButton.setSizePolicy(sizePolicy)
        self.rectangleButton.setMinimumSize(QtCore.QSize(58, 41))
        self.rectangleButton.setMaximumSize(QtCore.QSize(58, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/rect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectangleButton.setIcon(icon5)
        self.rectangleButton.setIconSize(QtCore.QSize(35, 35))
        self.rectangleButton.setCheckable(True)
        self.rectangleButton.setAutoExclusive(True)
        self.rectangleButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.rectangleButton.setAutoRaise(True)
        self.rectangleButton.setObjectName(_fromUtf8("rectangleButton"))
        self.gridLayout.addWidget(self.rectangleButton, 2, 0, 1, 1)
        self.circleButton = QtGui.QToolButton(self.navwidget)
        self.circleButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circleButton.sizePolicy().hasHeightForWidth())
        self.circleButton.setSizePolicy(sizePolicy)
        self.circleButton.setMinimumSize(QtCore.QSize(58, 41))
        self.circleButton.setMaximumSize(QtCore.QSize(58, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/cerchio.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.circleButton.setIcon(icon6)
        self.circleButton.setIconSize(QtCore.QSize(35, 35))
        self.circleButton.setCheckable(True)
        self.circleButton.setAutoExclusive(True)
        self.circleButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.circleButton.setAutoRaise(True)
        self.circleButton.setObjectName(_fromUtf8("circleButton"))
        self.gridLayout.addWidget(self.circleButton, 2, 1, 1, 1)
        self.line = QtGui.QFrame(self.navwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 2)
        self.radioList = QtGui.QRadioButton(self.navwidget)
        self.radioList.setMinimumSize(QtCore.QSize(50, 0))
        self.radioList.setMaximumSize(QtCore.QSize(50, 16777215))
        self.radioList.setChecked(True)
        self.radioList.setObjectName(_fromUtf8("radioList"))
        self.gridLayout.addWidget(self.radioList, 4, 0, 1, 1)
        self.radioNew = QtGui.QRadioButton(self.navwidget)
        self.radioNew.setMinimumSize(QtCore.QSize(50, 0))
        self.radioNew.setMaximumSize(QtCore.QSize(60, 16777215))
        self.radioNew.setObjectName(_fromUtf8("radioNew"))
        self.gridLayout.addWidget(self.radioNew, 4, 1, 1, 1)
        self.scrollAreaMarker = QtGui.QScrollArea(self.navwidget)
        self.scrollAreaMarker.setMinimumSize(QtCore.QSize(140, 51))
        self.scrollAreaMarker.setMaximumSize(QtCore.QSize(140, 51))
        self.scrollAreaMarker.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaMarker.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollAreaMarker.setWidgetResizable(True)
        self.scrollAreaMarker.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollAreaMarker.setObjectName(_fromUtf8("scrollAreaMarker"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(5, 0, 111, 185))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(111, 185))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(111, 53))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.diamond = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.diamond.setMinimumSize(QtCore.QSize(30, 30))
        self.diamond.setMaximumSize(QtCore.QSize(30, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Diamond.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.diamond.setIcon(icon7)
        self.diamond.setIconSize(QtCore.QSize(30, 30))
        self.diamond.setCheckable(True)
        self.diamond.setAutoExclusive(True)
        self.diamond.setAutoRaise(True)
        self.diamond.setObjectName(_fromUtf8("diamond"))
        self.gridLayout_3.addWidget(self.diamond, 2, 0, 1, 1)
        self.regular_star = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.regular_star.setMinimumSize(QtCore.QSize(30, 30))
        self.regular_star.setMaximumSize(QtCore.QSize(30, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/whiteStar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.regular_star.setIcon(icon8)
        self.regular_star.setIconSize(QtCore.QSize(30, 30))
        self.regular_star.setCheckable(True)
        self.regular_star.setChecked(True)
        self.regular_star.setAutoExclusive(True)
        self.regular_star.setAutoRaise(True)
        self.regular_star.setObjectName(_fromUtf8("regular_star"))
        self.gridLayout_3.addWidget(self.regular_star, 1, 0, 1, 1)
        self.circle = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.circle.setMinimumSize(QtCore.QSize(30, 30))
        self.circle.setMaximumSize(QtCore.QSize(30, 30))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Circle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.circle.setIcon(icon9)
        self.circle.setIconSize(QtCore.QSize(30, 30))
        self.circle.setCheckable(True)
        self.circle.setAutoExclusive(True)
        self.circle.setAutoRaise(True)
        self.circle.setObjectName(_fromUtf8("circle"))
        self.gridLayout_3.addWidget(self.circle, 1, 1, 1, 1)
        self.rectangle = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.rectangle.setMinimumSize(QtCore.QSize(30, 30))
        self.rectangle.setMaximumSize(QtCore.QSize(30, 30))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Square.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectangle.setIcon(icon10)
        self.rectangle.setIconSize(QtCore.QSize(30, 30))
        self.rectangle.setCheckable(True)
        self.rectangle.setAutoExclusive(True)
        self.rectangle.setAutoRaise(True)
        self.rectangle.setObjectName(_fromUtf8("rectangle"))
        self.gridLayout_3.addWidget(self.rectangle, 2, 1, 1, 1)
        self.cross = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.cross.setMinimumSize(QtCore.QSize(30, 30))
        self.cross.setMaximumSize(QtCore.QSize(30, 30))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Cross2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cross.setIcon(icon11)
        self.cross.setIconSize(QtCore.QSize(30, 30))
        self.cross.setCheckable(True)
        self.cross.setAutoExclusive(True)
        self.cross.setAutoRaise(True)
        self.cross.setObjectName(_fromUtf8("cross"))
        self.gridLayout_3.addWidget(self.cross, 3, 0, 1, 1)
        self.triangle = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.triangle.setMinimumSize(QtCore.QSize(30, 30))
        self.triangle.setMaximumSize(QtCore.QSize(30, 30))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Triangolo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.triangle.setIcon(icon12)
        self.triangle.setIconSize(QtCore.QSize(30, 30))
        self.triangle.setCheckable(True)
        self.triangle.setAutoExclusive(True)
        self.triangle.setAutoRaise(True)
        self.triangle.setObjectName(_fromUtf8("triangle"))
        self.gridLayout_3.addWidget(self.triangle, 3, 1, 1, 1)
        self.filled_arrowhead = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.filled_arrowhead.setMinimumSize(QtCore.QSize(30, 30))
        self.filled_arrowhead.setMaximumSize(QtCore.QSize(30, 30))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Triangolo2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filled_arrowhead.setIcon(icon13)
        self.filled_arrowhead.setIconSize(QtCore.QSize(30, 30))
        self.filled_arrowhead.setCheckable(True)
        self.filled_arrowhead.setAutoExclusive(True)
        self.filled_arrowhead.setAutoRaise(True)
        self.filled_arrowhead.setObjectName(_fromUtf8("filled_arrowhead"))
        self.gridLayout_3.addWidget(self.filled_arrowhead, 4, 0, 1, 1)
        self.arrow = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.arrow.setMinimumSize(QtCore.QSize(30, 30))
        self.arrow.setMaximumSize(QtCore.QSize(30, 30))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Freccia.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow.setIcon(icon14)
        self.arrow.setIconSize(QtCore.QSize(30, 30))
        self.arrow.setCheckable(True)
        self.arrow.setAutoExclusive(True)
        self.arrow.setAutoRaise(True)
        self.arrow.setObjectName(_fromUtf8("arrow"))
        self.gridLayout_3.addWidget(self.arrow, 4, 1, 1, 1)
        self.pentagon = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.pentagon.setMinimumSize(QtCore.QSize(30, 30))
        self.pentagon.setMaximumSize(QtCore.QSize(30, 30))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Penta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pentagon.setIcon(icon15)
        self.pentagon.setIconSize(QtCore.QSize(30, 30))
        self.pentagon.setCheckable(True)
        self.pentagon.setAutoExclusive(True)
        self.pentagon.setAutoRaise(True)
        self.pentagon.setObjectName(_fromUtf8("pentagon"))
        self.gridLayout_3.addWidget(self.pentagon, 5, 0, 1, 1)
        self.arrowhead = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.arrowhead.setMinimumSize(QtCore.QSize(30, 30))
        self.arrowhead.setMaximumSize(QtCore.QSize(30, 30))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/Freccia_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrowhead.setIcon(icon16)
        self.arrowhead.setIconSize(QtCore.QSize(30, 30))
        self.arrowhead.setCheckable(True)
        self.arrowhead.setAutoExclusive(True)
        self.arrowhead.setAutoRaise(True)
        self.arrowhead.setObjectName(_fromUtf8("arrowhead"))
        self.gridLayout_3.addWidget(self.arrowhead, 5, 1, 1, 1)
        self.scrollAreaMarker.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollAreaMarker, 5, 0, 1, 2)
        self.StyleList = QtGui.QComboBox(self.navwidget)
        self.StyleList.setMinimumSize(QtCore.QSize(135, 20))
        self.StyleList.setMaximumSize(QtCore.QSize(135, 20))
        self.StyleList.setStyleSheet(_fromUtf8("background: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #eef, stop: 1 #ccf);\n"
"border-radius: 4px;\n"
"font: 12pt \"Arial\";\n"
"\n"
""))
        self.StyleList.setObjectName(_fromUtf8("StyleList"))
        self.gridLayout.addWidget(self.StyleList, 6, 0, 1, 2)
        self.Textinput = QtGui.QLineEdit(self.navwidget)
        self.Textinput.setMinimumSize(QtCore.QSize(135, 20))
        self.Textinput.setMaximumSize(QtCore.QSize(135, 20))
        self.Textinput.setStyleSheet(_fromUtf8("background: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #eef, stop: 1 #ccf);\n"
"border-radius: 4px;\n"
"font: 12pt \"Arial\";"))
        self.Textinput.setObjectName(_fromUtf8("Textinput"))
        self.gridLayout.addWidget(self.Textinput, 7, 0, 1, 2)
        self.Transparency = QtGui.QSlider(self.navwidget)
        self.Transparency.setMinimumSize(QtCore.QSize(135, 0))
        self.Transparency.setMaximumSize(QtCore.QSize(135, 30))
        self.Transparency.setTracking(True)
        self.Transparency.setOrientation(QtCore.Qt.Horizontal)
        self.Transparency.setTickPosition(QtGui.QSlider.TicksAbove)
        self.Transparency.setTickInterval(10)
        self.Transparency.setObjectName(_fromUtf8("Transparency"))
        self.gridLayout.addWidget(self.Transparency, 8, 0, 1, 2)
        self.StyleLine = QtGui.QComboBox(self.navwidget)
        self.StyleLine.setMinimumSize(QtCore.QSize(135, 20))
        self.StyleLine.setMaximumSize(QtCore.QSize(135, 20))
        self.StyleLine.setAutoFillBackground(False)
        self.StyleLine.setStyleSheet(_fromUtf8("background: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #eef, stop: 1 #ccf);\n"
"border-radius: 4px;\n"
"font: 12pt \"Arial\";"))
        self.StyleLine.setObjectName(_fromUtf8("StyleLine"))
        self.gridLayout.addWidget(self.StyleLine, 9, 0, 1, 2)
        self.outlineSize = QtGui.QSlider(self.navwidget)
        self.outlineSize.setMinimumSize(QtCore.QSize(135, 0))
        self.outlineSize.setMaximumSize(QtCore.QSize(135, 30))
        self.outlineSize.setTracking(True)
        self.outlineSize.setOrientation(QtCore.Qt.Horizontal)
        self.outlineSize.setTickPosition(QtGui.QSlider.TicksAbove)
        self.outlineSize.setTickInterval(10)
        self.outlineSize.setObjectName(_fromUtf8("outlineSize"))
        self.gridLayout.addWidget(self.outlineSize, 10, 0, 1, 2)
        self.checkLineTransparency = QtGui.QCheckBox(self.navwidget)
        self.checkLineTransparency.setMinimumSize(QtCore.QSize(130, 20))
        self.checkLineTransparency.setMaximumSize(QtCore.QSize(130, 20))
        self.checkLineTransparency.setStyleSheet(_fromUtf8("QCheckBox{font: 11pt \"Arial\";}\n"
"QCheckBox:indicator {width: 15px; height: 15px; }"))
        self.checkLineTransparency.setObjectName(_fromUtf8("checkLineTransparency"))
        self.gridLayout.addWidget(self.checkLineTransparency, 11, 0, 1, 2)
        self.LineColor = QtGui.QPushButton(self.navwidget)
        self.LineColor.setMinimumSize(QtCore.QSize(140, 30))
        self.LineColor.setMaximumSize(QtCore.QSize(140, 30))
        self.LineColor.setStyleSheet(_fromUtf8("QPushButton{\n"
"background-color:black;\n"
"border:2px solid rgb(180, 180, 180);\n"
"border-radius: 4px;\n"
"font: bold 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background: qlineargradient(x1 : 0, y1 : 0, x2 : 0, y2 :   1, stop :   0.0 #ffd9aa, stop :   0.5 #ffbb6e, stop :   0.55 #feae42, stop :   1.0 #fedb74);\n"
"}"))
        self.LineColor.setObjectName(_fromUtf8("LineColor"))
        self.gridLayout.addWidget(self.LineColor, 12, 0, 1, 2)
        self.Size = QtGui.QSlider(self.navwidget)
        self.Size.setMinimumSize(QtCore.QSize(135, 0))
        self.Size.setMaximumSize(QtCore.QSize(135, 24))
        self.Size.setMouseTracking(True)
        self.Size.setTracking(True)
        self.Size.setOrientation(QtCore.Qt.Horizontal)
        self.Size.setTickPosition(QtGui.QSlider.TicksAbove)
        self.Size.setTickInterval(10)
        self.Size.setObjectName(_fromUtf8("Size"))
        self.gridLayout.addWidget(self.Size, 13, 0, 1, 2)
        self.checkFillTransparency = QtGui.QCheckBox(self.navwidget)
        self.checkFillTransparency.setMinimumSize(QtCore.QSize(130, 15))
        self.checkFillTransparency.setMaximumSize(QtCore.QSize(130, 15))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.checkFillTransparency.setFont(font)
        self.checkFillTransparency.setStyleSheet(_fromUtf8("QCheckBox{font: 11pt \"Arial\";}\n"
"QCheckBox:indicator {width: 15px; height: 15px; }"))
        self.checkFillTransparency.setObjectName(_fromUtf8("checkFillTransparency"))
        self.gridLayout.addWidget(self.checkFillTransparency, 14, 0, 1, 2)
        self.color = QtGui.QPushButton(self.navwidget)
        self.color.setMinimumSize(QtCore.QSize(140, 30))
        self.color.setMaximumSize(QtCore.QSize(140, 30))
        self.color.setStyleSheet(_fromUtf8("QPushButton {\n"
"background-color:transparent;\n"
"border:2px  solid rgb(180, 180, 180);\n"
"border-radius: 4px;\n"
"font: bold 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background: qlineargradient(x1 : 0, y1 : 0, x2 : 0, y2 :   1, stop :   0.0 #ffd9aa, stop :   0.5 #ffbb6e, stop :   0.55 #feae42, stop :   1.0 #fedb74);\n"
"}"))
        self.color.setObjectName(_fromUtf8("color"))
        self.gridLayout.addWidget(self.color, 15, 0, 1, 2)
        self.line_2 = QtGui.QFrame(self.navwidget)
        self.line_2.setMaximumSize(QtCore.QSize(140, 16777215))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 16, 0, 1, 2)
        self.endButton = QtGui.QToolButton(self.navwidget)
        self.endButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endButton.sizePolicy().hasHeightForWidth())
        self.endButton.setSizePolicy(sizePolicy)
        self.endButton.setMinimumSize(QtCore.QSize(58, 41))
        self.endButton.setMaximumSize(QtCore.QSize(58, 41))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/stop-01.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.endButton.setIcon(icon17)
        self.endButton.setIconSize(QtCore.QSize(35, 35))
        self.endButton.setAutoRaise(True)
        self.endButton.setObjectName(_fromUtf8("endButton"))
        self.gridLayout.addWidget(self.endButton, 17, 0, 1, 1)
        self.refreshButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshButton.sizePolicy().hasHeightForWidth())
        self.refreshButton.setSizePolicy(sizePolicy)
        self.refreshButton.setMinimumSize(QtCore.QSize(58, 41))
        self.refreshButton.setMaximumSize(QtCore.QSize(58, 41))
        self.refreshButton.setStyleSheet(_fromUtf8(""))
        self.refreshButton.setText(_fromUtf8(""))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon18)
        self.refreshButton.setIconSize(QtCore.QSize(35, 35))
        self.refreshButton.setAutoRaise(True)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.gridLayout.addWidget(self.refreshButton, 17, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.navwidget)
        self.line_3.setMinimumSize(QtCore.QSize(140, 0))
        self.line_3.setMaximumSize(QtCore.QSize(140, 16777215))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 18, 0, 1, 2)
        self.deleteButton_2 = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton_2.sizePolicy().hasHeightForWidth())
        self.deleteButton_2.setSizePolicy(sizePolicy)
        self.deleteButton_2.setMinimumSize(QtCore.QSize(140, 41))
        self.deleteButton_2.setMaximumSize(QtCore.QSize(140, 41))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/eraser")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton_2.setIcon(icon19)
        self.deleteButton_2.setIconSize(QtCore.QSize(35, 35))
        self.deleteButton_2.setCheckable(True)
        self.deleteButton_2.setAutoRaise(True)
        self.deleteButton_2.setObjectName(_fromUtf8("deleteButton_2"))
        self.gridLayout.addWidget(self.deleteButton_2, 19, 0, 1, 2)
        self.undoButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undoButton.sizePolicy().hasHeightForWidth())
        self.undoButton.setSizePolicy(sizePolicy)
        self.undoButton.setMinimumSize(QtCore.QSize(50, 41))
        self.undoButton.setMaximumSize(QtCore.QSize(58, 41))
        self.undoButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoButton.setIcon(icon20)
        self.undoButton.setIconSize(QtCore.QSize(35, 35))
        self.undoButton.setAutoRaise(True)
        self.undoButton.setObjectName(_fromUtf8("undoButton"))
        self.gridLayout.addWidget(self.undoButton, 20, 0, 1, 1)
        self.redoButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redoButton.sizePolicy().hasHeightForWidth())
        self.redoButton.setSizePolicy(sizePolicy)
        self.redoButton.setMinimumSize(QtCore.QSize(58, 41))
        self.redoButton.setMaximumSize(QtCore.QSize(58, 41))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/symbol/resources/images/simboli/redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoButton.setIcon(icon21)
        self.redoButton.setIconSize(QtCore.QSize(35, 35))
        self.redoButton.setAutoRaise(True)
        self.redoButton.setObjectName(_fromUtf8("redoButton"))
        self.gridLayout.addWidget(self.redoButton, 20, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(135, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem, 21, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.closeBarButton, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.infoframe.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Draw Point</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.closeBarButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Close ToolBar</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.closeBarButton.setText(QtGui.QApplication.translate("Form", "Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.PointButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Draw Point</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.PointButton.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.paintButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Paint</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.paintButton.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Draw Line</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.polyButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Draw Polygon</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.polyButton.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.rectangleButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Draw Rectangle</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rectangleButton.setAccessibleDescription(QtGui.QApplication.translate("Form", "rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.circleButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Draw Circle</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.radioList.setText(QtGui.QApplication.translate("Form", "list", None, QtGui.QApplication.UnicodeUTF8))
        self.radioNew.setText(QtGui.QApplication.translate("Form", "new", None, QtGui.QApplication.UnicodeUTF8))
        self.scrollAreaMarker.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Point Type</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.diamond.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.regular_star.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.circle.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.rectangle.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.cross.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.triangle.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.filled_arrowhead.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.arrow.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pentagon.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.arrowhead.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.StyleList.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Line Style</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Textinput.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Style Label</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Transparency.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Transparency</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.StyleLine.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Line Style</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.outlineSize.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Size Line</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLineTransparency.setText(QtGui.QApplication.translate("Form", "No Stroke Color", None, QtGui.QApplication.UnicodeUTF8))
        self.LineColor.setText(QtGui.QApplication.translate("Form", "Stroke Color", None, QtGui.QApplication.UnicodeUTF8))
        self.Size.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Size</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkFillTransparency.setText(QtGui.QApplication.translate("Form", "No Fill Color", None, QtGui.QApplication.UnicodeUTF8))
        self.color.setText(QtGui.QApplication.translate("Form", "Fill Color", None, QtGui.QApplication.UnicodeUTF8))
        self.endButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Stop and Draw</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Cancel</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton_2.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Delete</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton_2.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Undo</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Redo</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
