# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\sviluppo\Roam\src\roam\ui\ui_infodock.ui'
#
# Created: Thu Mar 12 14:47:58 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(625, 697)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.layerList = QtGui.QListWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerList.sizePolicy().hasHeightForWidth())
        self.layerList.setSizePolicy(sizePolicy)
        self.layerList.setStyleSheet(_fromUtf8(""))
        self.layerList.setFrameShape(QtGui.QFrame.NoFrame)
        self.layerList.setObjectName(_fromUtf8("layerList"))
        self.gridLayout.addWidget(self.layerList, 0, 0, 1, 1)
        self.infoframe = QtGui.QFrame(Form)
        self.infoframe.setAutoFillBackground(True)
        self.infoframe.setFrameShape(QtGui.QFrame.NoFrame)
        self.infoframe.setFrameShadow(QtGui.QFrame.Raised)
        self.infoframe.setObjectName(_fromUtf8("infoframe"))
        self.gridLayout_2 = QtGui.QGridLayout(self.infoframe)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.attributesView = QtWebKit.QWebView(self.infoframe)
        self.attributesView.setBaseSize(QtCore.QSize(100, 0))
        self.attributesView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.attributesView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.attributesView.setObjectName(_fromUtf8("attributesView"))
        self.gridLayout_2.addWidget(self.attributesView, 2, 0, 1, 1)
        self.navwidget = QtGui.QWidget(self.infoframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navwidget.sizePolicy().hasHeightForWidth())
        self.navwidget.setSizePolicy(sizePolicy)
        self.navwidget.setObjectName(_fromUtf8("navwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.navwidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.editButton = QtGui.QToolButton(self.navwidget)
        self.editButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editButton.setIcon(icon)
        self.editButton.setIconSize(QtCore.QSize(48, 48))
        self.editButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.editButton.setAutoRaise(True)
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.horizontalLayout_3.addWidget(self.editButton)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.editGeomButton = QtGui.QToolButton(self.navwidget)
        self.editGeomButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/editgeom")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editGeomButton.setIcon(icon1)
        self.editGeomButton.setIconSize(QtCore.QSize(48, 48))
        self.editGeomButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.editGeomButton.setAutoRaise(True)
        self.editGeomButton.setObjectName(_fromUtf8("editGeomButton"))
        self.horizontalLayout_3.addWidget(self.editGeomButton)
        self.expandButton = QtGui.QToolButton(self.navwidget)
        self.expandButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/expand")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expandButton.setIcon(icon2)
        self.expandButton.setIconSize(QtCore.QSize(48, 48))
        self.expandButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.expandButton.setAutoRaise(True)
        self.expandButton.setObjectName(_fromUtf8("expandButton"))
        self.horizontalLayout_3.addWidget(self.expandButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.closeButton = QtGui.QToolButton(self.navwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cancel")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setIconSize(QtCore.QSize(48, 48))
        self.closeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.closeButton.setAutoRaise(True)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.gridLayout_2.addWidget(self.navwidget, 0, 0, 1, 1)
        self.bottomWidget = QtGui.QWidget(self.infoframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomWidget.sizePolicy().hasHeightForWidth())
        self.bottomWidget.setSizePolicy(sizePolicy)
        self.bottomWidget.setObjectName(_fromUtf8("bottomWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.bottomWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2.addWidget(self.bottomWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.infoframe, 0, 1, 2, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 71, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import resources_rc
